---
# This Playbook runs all the common plays in the deployment

- name: Create the hosts file for all machines
  sudo: yes
  template: src=hosts.j2 dest=/etc/hosts

- name: Install python-pip
  become: yes
  apt: pkg=python-pip state=present

- name: Install the latest pymongo package
  pip: name=pymongo state=latest use_mirrors=no

- name: Add Mongo repo key
  sudo: yes
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  tags:
    - setup
    - setupMongo

- name: Add repository
  shell: echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  sudo : yes
  tags:
    - setup
    - setupMongo

- name: Install latest MongoDB release
  apt: pkg=mongodb-org state=present update_cache=yes
  sudo : yes
  tags:
    - setup
    - setupMongo

#
# - name: Create run directory for mongodb - Make sure that the run temp file directory gets created by systemd on reboot
#   copy: src=mongod_tempfiles.conf dest=/lib/tmpfiles.d/mongod_tempfiles.conf
#
# - name: Create run directory - do it now
#   command: systemd-tmpfiles --create mongod_tempfiles.conf
#


- name: Sync config file
  action: template src=mongodb.conf.j2 dest=/etc/mongod.conf mode=0644 owner=mongodb
  sudo : yes
  notify:
    - restart mongod
  tags:
    - setup
    - setupMongo

- name: MONGODB | create unit file for systemctl
  action: template src=mongo_unit.j2 dest=/etc/systemd/system/mongod.service
  sudo: yes
  tags:
    - setup
    - setupMongo

- name: Set up the mongodb service using systemd
  become: yes
  command: systemctl --system daemon-reload
  command: systemctl enable mongod.service

#
# - name: MongoDB | Ensure deamon is running correctly
#   service: name=mongod state=restarted
#   sudo : yes
#   tags:
#     - setup
#     - setupMongo

#
# - name: Create the hosts file for all machines
#   template: src=hosts.j2 dest=/etc/hosts
#
# - name: Create the repository for 10Gen
#   copy: src=10gen.repo.j2 dest=/etc/yum.repos.d/10gen.repo
#
# - name: Create the EPEL Repository.
#   copy: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo
#
# - name: Create the GPG key for EPEL
#   copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg
#
# - name: Create the mongod user
#   user: name=mongod comment="MongoD"
#
# - name: Create the data directory for the namenode metadata
#   file: path={{ mongodb_datadir_prefix }} owner=mongod group=mongod state=directory
#
# - name: Install the mongodb package
#   yum: name={{ item }} state=installed
#   with_items:
#    - libselinux-python
#    - mongodb-org
#    - mongodb-org-server
#    - bc
#    - python-pip
#    - ntp
#
# - name: Enable NTPD
#   service: name=ntpd enabled=yes state=started
#
# - name: Install the latest pymongo package
#   pip: name=pymongo state=latest use_mirrors=no
#
# # Disable transparent_hugepages
# - name: Disable transparent_hugepages, create the profile directory for tuned (1/3)
#   file: path=/etc/tuned/no-thp state=directory
#
# - name: Copy the tuned.conf to the new directory (2/3)
#   copy: src=tuned.conf dest=/etc/tuned/no-thp
#
# - name: Enable the new profile
#   command: tuned-adm profile no-thp
